app = 'unprompted'
primary_region = 'ord'

[build]

[deploy]
  strategy = 'bluegreen'
  wait_timeout = '5m'

kill_timeout = 30

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1


[[vm]]
  size = 'performance-1x'
  memory = '8192mb'
